import "./globals.scss";
import Providers from "./store/provider";
import { Alert } from "@/components/Alert";
import { ThemeProvider } from "styled-components";
import ThemeProviders from "@/components/theme/themeProvider";
export const metadata = {
  title: "NestXm",
  description: "Generated by xavier mayora",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Providers>
        <body>
            {children}
            <Alert />
        </body>
      </Providers>
    </html>
  );
}
