import "./globals.scss";
import "../services/axios";
import { Alert } from "@/components/Alert";
import Dashboard from "@/components/Dashboard";

import Providers from "./store/provider";
export const metadata = {
  title: "NestXm",
  description: "Generated by xavier mayora",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Providers>
        <body>
          <Dashboard>{children}</Dashboard>
          <Alert />
        </body>
      </Providers>
    </html>
  );
}
